In [2]:
import tensorflow as tf

In [6]:
# int contant
a=tf.constant(10)
a

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [7]:
# float constant
b=tf.constant(20.0)
b

<tf.Tensor: shape=(), dtype=float32, numpy=20.0>

In [8]:
# string constant
c=tf.constant("hello")
c

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [9]:
# create numpy array
import numpy as np

In [10]:
numpy_arr=tf.constant(np.array([1,2,3,4,5]))
numpy_arr

<tf.Tensor: shape=(5,), dtype=int64, numpy=array([1, 2, 3, 4, 5])>

In [12]:
# create 2d aray
numpy_arr=tf.constant(np.array([[1,2,3,4,5],[1,3,4,6,7]]))
numpy_arr

<tf.Tensor: shape=(2, 5), dtype=int64, numpy=
array([[1, 2, 3, 4, 5],
       [1, 3, 4, 6, 7]])>

In [15]:
# sahpe of 2d aray
numpy_arr=tf.constant([1,2,3,4],shape=(2,2))
numpy_arr

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [16]:
# acces constant value
numpy_arr.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)