In [ ]:
# create tensorfloq
import tensorflow as tf

In [ ]:
# execution compat.v1.disable_eager_execution
tf.compat.v1.disable_eager_execution()

In [ ]:
# create placeholed
a=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))

a


<tf.Tensor 'Placeholder_1:0' shape=(400, 400) dtype=float32>

In [ ]:
b=tf.compat.v1.placeholder(dtype=tf.float32,shape=(400,400))
b

<tf.Tensor 'Placeholder_2:0' shape=(400, 400) dtype=float32>

# ***add***

In [ ]:
c=tf.add(a,b)
c

<tf.Tensor 'Add:0' shape=(400, 400) dtype=float32>

# create numpy array

In [ ]:
import numpy as np
num_arr=np.ones((400,400),np.float32)
num_arr

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], dtype=float32)

execution tensorflow placeholder using session
## New Section

In [ ]:
with tf.compat.v1.Session() as sess:
  print(sess.run(c,feed_dict={a:num_arr,b:num_arr}))

[[2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 ...
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]
 [2. 2. 2. ... 2. 2. 2.]]
