In [1]:
# CREAATE VARIBALAE
import tensorflow as tf

In [2]:
# create variable
a=tf.Variable(1)
a

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [3]:
# check name
a.name , a.shape , a.dtype

('Variable:0', TensorShape([]), tf.int32)

In [4]:
# create list
b=tf.Variable([1,2,3])
b

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [5]:
# create string
c=tf.Variable('hello')
c

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'hello'>

In [6]:
# create int,float
d=tf.Variable([1.2,6,1.3,45.4])
d

<tf.Variable 'Variable:0' shape=(4,) dtype=float32, numpy=array([ 1.2,  6. ,  1.3, 45.4], dtype=float32)>

In [7]:
d.numpy()

array([ 1.2,  6. ,  1.3, 45.4], dtype=float32)

create variable from **constant**

In [8]:
tf_constan=tf.constant([1,2,3])
tf_constan

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [9]:
tf_var=tf.Variable(tf_constan)
tf_var

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

# create multiple matrix

In [10]:
tf_2d=tf.Variable([[2,3,4,5],[4,5,6,7]],dtype="float32",shape=(2,4))
tf_2d

<tf.Variable 'Variable:0' shape=(2, 4) dtype=float32, numpy=
array([[2., 3., 4., 5.],
       [4., 5., 6., 7.]], dtype=float32)>

In [11]:
tf.reshape(tf_2d,[4,2])

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[2., 3.],
       [4., 5.],
       [4., 5.],
       [6., 7.]], dtype=float32)>

# **ccheck the shape**

In [12]:
tf.reshape(tf_2d,(2,4))


<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[2., 3., 4., 5.],
       [4., 5., 6., 7.]], dtype=float32)>

# ***convert as a tensor***

In [13]:
tf_1=tf.Variable([1,2,3])
tf_1

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [14]:
m=tf.convert_to_tensor(tf_1)

# ***assign a new value***

In [16]:
# Create a variable
r = tf.Variable([1, 2, 3], dtype=tf.int32)

# Use the assign method to update its value
r.assign([4, 5, 6])

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([4, 5, 6], dtype=int32)>